tweak CHROMEDRIVER_VERSION

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,23 +1,88 @@
 #!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir> <env-dir>
 
+# fail fast
+set -e
+set -o pipefail
+
+# debug
+# set -x
+
+# parse and derive params
+BUILD_DIR=$1
+CACHE_DIR=$2
+ENV_DIR=$3
+BUILDPACK_DIR="$(cd "$(dirname "$0")"; cd ..; pwd)"
 CHROME_VERSION="128.0.0.0"  # Chromeバージョンを指定
 CHROMEDRIVER_VERSION="128.0.0"  # ChromeDriverバージョンを指定
 
-BUILD_DIR=$1
+function error() {
+  echo " !     $*" >&2
+  exit 1
+}
 
-echo "-----> Installing Chrome version ${CHROME_VERSION}"
+function topic() {
+  echo "-----> $*"
+}
 
-# Chromeのインストール
-curl -o /tmp/google-chrome-stable_${CHROME_VERSION}_amd64.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb
-dpkg -x /tmp/google-chrome-stable_${CHROME_VERSION}_amd64.deb $BUILD_DIR/.apt/
-rm /tmp/google-chrome-stable_${CHROME_VERSION}_amd64.deb
+function indent() {
+  c='s/^/       /'
+  case $(uname) in
+    Darwin) sed -l "$c";;
+    *)      sed -u "$c";;
+  esac
+}
 
-# ChromeDriverのインストール
-echo "-----> Installing ChromeDriver version ${CHROMEDRIVER_VERSION}"
-curl -o /tmp/chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
-unzip /tmp/chromedriver_linux64.zip -d $BUILD_DIR/.apt/usr/bin
-rm /tmp/chromedriver_linux64.zip
+topic "Installing Chrome for Testing"
 
-# 環境変数の設定
-echo "export GOOGLE_CHROME_BIN=$BUILD_DIR/.apt/opt/google/chrome/chrome" > $BUILD_DIR/.profile.d/chrome.sh
-echo "export CHROMEDRIVER_PATH=$BUILD_DIR/.apt/usr/bin/chromedriver" >> $BUILD_DIR/.profile.d/chrome.sh
+INSTALL_DIR="$BUILD_DIR/.chrome-for-testing"
+mkdir -p "$INSTALL_DIR"
+
+# Detect if the old config var is still used
+if [ -f "$CHROMEDRIVER_VERSION" ]; then
+  error "This buildpack no longer supports CHROMEDRIVER_VERSION config var and must be removed to continue, because this buildpack now installs compatible versions of Chrome & Chromedriver. GOOGLE_CHROME_CHANNEL can be used to set Stable (default), Beta, Dev, or Canary."
+fi
+
+# Detect if Chrome is already installed
+if which chrome; then
+  error "Chrome is already installed. This buildpack now installs a compatible version of Chrome. Please, remove the other Chrome installation. Chrome may have been installed by another buildpack (such as heroku/heroku-buildpack-google-chrome buildpack), which should no longer be used with this buildpack."
+fi
+
+# Detect requested channel or default to stable
+if [ -f "$ENV_DIR/GOOGLE_CHROME_CHANNEL" ]; then
+  channel=$(cat "$ENV_DIR/GOOGLE_CHROME_CHANNEL")
+  echo "Using env var GOOGLE_CHROME_CHANNEL=$channel" | indent
+else
+  channel=stable
+fi
+# The current version endpoint requires ALL CAPS.
+CHANNEL="$(echo -n "$channel" | awk '{ print toupper($0) }')"
+VERSION="$(curl --silent --show-error --fail --retry 3 --retry-connrefused --connect-timeout 10 "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_$CHANNEL")"
+echo "Resolved $CHANNEL version $VERSION" | indent
+
+echo "Downloading Chrome" | indent
+ZIP_URL="https://storage.googleapis.com/chrome-for-testing-public/$VERSION/linux64/chrome-linux64.zip"
+ZIP_LOCATION="$INSTALL_DIR/chrome.zip"
+curl --silent --show-error --fail --retry 3 --retry-connrefused --connect-timeout 10 -o "${ZIP_LOCATION}" "${ZIP_URL}" | indent
+unzip -q -o "$ZIP_LOCATION" -d "$INSTALL_DIR" | indent
+rm -f "$ZIP_LOCATION"
+
+echo "Downloading Chromedriver" | indent
+ZIP_URL="https://storage.googleapis.com/chrome-for-testing-public/$VERSION/linux64/chromedriver-linux64.zip"
+ZIP_LOCATION="$INSTALL_DIR/chromedriver.zip"
+curl --silent --show-error --fail --retry 3 --retry-connrefused --connect-timeout 10 -o "${ZIP_LOCATION}" "${ZIP_URL}" | indent
+unzip -q -o "$ZIP_LOCATION" -d "$INSTALL_DIR" | indent
+rm -f "$ZIP_LOCATION"
+
+source "$BUILDPACK_DIR/bin/install-chrome-dependencies"
+
+echo "Adding executables to PATH" | indent
+mkdir -p "$BUILD_DIR/.profile.d"
+echo "export PATH=\$HOME/.chrome-for-testing/chrome-linux64:\$HOME/.chrome-for-testing/chromedriver-linux64:\$PATH" >> "$BUILD_DIR/.profile.d/chrome-for-testing.sh"
+
+# Verify the executables are actually present
+export PATH="$BUILD_DIR/.chrome-for-testing/chrome-linux64:$BUILD_DIR/.chrome-for-testing/chromedriver-linux64:$PATH"
+which chrome | indent
+which chromedriver | indent
+
+echo "Installed Chrome for Testing $CHANNEL version $VERSION" | indent
